general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands: ['shell-exec zebar']

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

  # How windows should be hidden when switching workspaces.
  # - 'cloak': Recommended. Hides windows with no animation.
  # - 'hide': Legacy method (v3.5 and earlier) that has a brief animation,
  # but has stability issues with some apps.
  hide_method: 'cloak'

  # Affects which windows get shown in the native Windows taskbar. Has no
  # effect if `hide_method: 'hide'`.
  # - 'true': Show all windows (regardless of workspace).
  # - 'false': Only show windows from the currently shown workspaces.
  show_all_in_taskbar: false

gaps:
  # Whether to scale the gaps with the DPI of the monitor.
  scale_with_dpi: true

  # Gap between adjacent windows.
  inner_gap: '10px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '30px'
    right: '10px'
    bottom: '10px'
    left: '10px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#8dbcff'

    # Remove the title bar from the window's frame. Note that this can
    # cause rendering issues for some applications.
    hide_title_bar:
      enabled: false

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: false
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'square'

    # Change the transparency of the window.
    transparency:
      enabled: false
      # Can be something like '95%' or '0.95' for slightly transparent windows.
      # '0' or '0%' is fully transparent (and, by consequence, unfocusable).
      opacity: '95%'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#a1a1a1'
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'square'
    transparency:
      enabled: false
      opacity: '0%'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
    display_name: "Misc"
  - name: '2'
    display_name: "Term (2)"
    bind_to_monitor: 1
    keep_alive: true
  - name: '3'
    display_name: "Browse (3)"
    bind_to_monitor: 0
    keep_alive: true
  - name: '4'
    display_name: "Talk (4)"
    bind_to_monitor: 0
    keep_alive: true
  - name: '5'
    display_name: "App (5)"
    bind_to_monitor: 0
    keep_alive: true
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'
  - name: '0'
  - name: 'm'

window_rules:
  - commands: ['move --workspace 5']
    match:
      - window_title: { equals: "zig-pong" }
  - commands: ['move --workspace 2']
    match:
      - window_title: { equals: "wezterm"}
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }
      - window_process: { equals: 'EXCEL' }
        window_class: { not_regex: 'XLMAIN' }
      - window_process: { equals: 'WINWORD' }
        window_class: { not_regex: 'OpusApp' }
      - window_process: { equals: 'POWERPNT' }
        window_class: { not_regex: 'PPTFrameClass' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+lwin+h']
  - commands: ['focus --direction right']
    bindings: ['alt+lwin+l']
  - commands: ['focus --direction up']
    bindings: ['alt+lwin+k']
  - commands: ['focus --direction down']
    bindings: ['alt+lwin+j']

  - commands: ['swap-workspace --workspace-in-direction left']
    bindings: ['alt+lwin+left']
  - commands: ['swap-workspace --workspace-in-direction right']
    bindings: ['alt+lwin+right', alt+lwin+tab]
  - commands: ['swap-workspace --workspace-in-direction up']
    bindings: ['alt+lwin+up']
  - commands: ['swap-workspace --workspace-in-direction down']
    bindings: ['alt+lwin+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+lwin+shift+h', 'alt+lwin+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+lwin+shift+l', 'alt+lwin+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+lwin+shift+k', 'alt+lwin+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+lwin+shift+j', 'alt+lwin+shift+down']
  #
  # Resize focused window by a percentage or pixel amount.
  # - commands: ['resize --width -2%']
  #   bindings: ['alt+lwin+u']
  # - commands: ['resize --width +2%']
  #   bindings: ['alt+lwin+p']
  # - commands: ['resize --height +2%']
  #   bindings: ['alt+lwin+o']
  # - commands: ['resize --height -2%']
  #   bindings: ['alt+lwin+i']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+lwin+shift+s']

  # Disables window management and all other keybindings until alt+lwin+shift+p
  # is pressed again.
  - commands: ['wm-toggle-pause']
    bindings: ['alt+lwin+shift+p']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+lwin+shift+d']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+lwin+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+lwin+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+lwin+shift+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+lwin+shift+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['alt+lwin+shift+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+lwin+shift+w']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+lwin+shift+q']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+lwin+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+lwin+shift+oem_plus'] # equal sign

  # Focus the next/previous active workspace defined in `workspaces` config.
  # - commands: ['focus --next-active-workspace']
  #   bindings: ['alt+lwin+s']
  # - commands: ['focus --prev-active-workspace']
  #   bindings: ['alt+lwin+a']

  # Focus the workspace that last had focus.
  # - commands: ['focus --recent-workspace']
  #   bindings: ['alt+lwin+d']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+lwin+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+lwin+2', 'alt+lwin+t']
  - commands: ['focus --workspace 3']
    bindings: ['alt+lwin+3', 'alt+lwin+i']
  - commands: ['focus --workspace 4']
    bindings: ['alt+lwin+4', 'alt+lwin+d']
  - commands: ['focus --workspace 5']
    bindings: ['alt+lwin+5']
  - commands: ['focus --workspace m']
    bindings: ['alt+lwin+m']
  - commands: ['focus --workspace 6']
    bindings: ['alt+lwin+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+lwin+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+lwin+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+lwin+9']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  # - commands: ['move-workspace --direction left']
  #   bindings: ['alt+lwin+shift+a']
  # - commands: ['move-workspace --direction right']
  #   bindings: ['alt+lwin+shift+f']
  # - commands: ['move-workspace --direction up']
  #   bindings: ['alt+lwin+shift+d']
  # - commands: ['move-workspace --direction down']
  #   bindings: ['alt+lwin+shift+s']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+lwin+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+lwin+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+lwin+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+lwin+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+lwin+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+lwin+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+lwin+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+lwin+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+lwin+shift+9']
